---
apiVersion: v1
kind: Namespace
metadata:
  name: eventing-sandbox
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: broker
  namespace: eventing-sandbox
---
apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: broker-config
  namespace: eventing-sandbox
spec:
  rabbitmqClusterReference:
    # Configure name if a RabbitMQ Cluster Operator is being used.
    name: broker
    # Configure connectionSecret if an external RabbitMQ cluster is being used.
    #connectionSecret:
    #  name: rabbitmq-secret-credentials
  queueType: quorum
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
  name: rabbitmq-broker
  namespace: eventing-sandbox
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: broker-config